@startuml Public Class Mastermind

class Mastermind{
    public Mastermind()
    public void play()
    public main()
}


class Board {
    Attemps [] attemps = new Attemps[10];
    CombinationSecret combinationSecret;

    public Board();
        
}

class Attemps {
 
   CombinationProposed combinationProposed = new CombinationProposed;

   public Attemps();   
   public string showresult();
}


class Combination {
    public Combination();
}

class CombinationProposed extends Combination{
    
    public CombinationProposed();
    public CombinationProposed read();
}

class CombinationSecret extends Combination{

    public CombinationSecret();   
    public boolean result(CombinationProposed combinationProposed)    
     
}

enum Colors {
    Red 
    Blue
    Yellow
    Green
    Orange
    Pink 
    Black
    White  
}


Mastermind *--> Board
Board "1" o--> "1" CombinationSecret
Board "1" o--> "10" Attemps
Attemps ..> CombinationProposed  
Combination *--> Colors
@enduml
